const ERROR_CODE_BAD_REQUEST = 400;
const ERROR_CODE_BAD_AUTH = 401;
const ERROR_CODE_BAD_PASSWORD = 403;
const ERROR_CODE_NOTE_FOUND = 404;
const ERROR_CODE_IS_FOUND = 409;
const ERROR_CODE_DEFAULT = 500;
const MONGO_DUPLICATE_ERROR_CODE = 11000;
const SALT_ROUNDS = 10;

module.exports = {
  ERROR_CODE_BAD_REQUEST,
  ERROR_CODE_NOTE_FOUND,
  ERROR_CODE_DEFAULT,
  MONGO_DUPLICATE_ERROR_CODE,
  SALT_ROUNDS,
  ERROR_CODE_IS_FOUND,
  ERROR_CODE_BAD_PASSWORD,
  ERROR_CODE_BAD_AUTH,
};
